version: '3'
services:
  pgsql:
    image: postgres
    restart: always
    env_file:
      - db.env
    volumes:
      - pgsql-data:/tmp/postgresql/data
      - ./sql/init-pgsql.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
volumes:
  pgsql-data: